### ISSUE TITLE
./post-provisioning.ps1 Fails

### ISSUE THREAD

**Issue by sqlshep** [microsoft/MCW-AI-led-business-process-automation#10] opened 2022-02-28 19:19 UTC
In Azure Cloud shell

Enter the name of the resource group you have created for your MCW environment.: "RG-MCW-AI"
Get-AzStorageAccount: /home/shep/MCW/Hands-on lab/lab-files/ARM-template/post-provisioning.ps1:17
Line |
  17 |  … ountName = (Get-AzureRmStorageAccount -ResourceGroupName $resourceGro …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 'resourceGroupName' does not match expected pattern '^[-\w\._\(\)]+$'.

Get-AzStorageAccountKey: /home/shep/MCW/Hands-on lab/lab-files/ARM-template/post-provisioning.ps1:18
Line |
  18 |  … GroupName $resourceGroupName -AccountName $storageAccountName).Value[ …
     |                                              ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the
     | command again.

New-AzStorageContext: /home/shep/MCW/Hands-on lab/lab-files/ARM-template/post-provisioning.ps1:19
Line |
  19 |  …  New-AzStorageContext -StorageAccountName $storageAccountName -Storag …
     |                                              ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'StorageAccountName'. The argument is null or empty. Provide an argument that is not null or empty, and
     | then try the command again.

New-AzStorageContainerSASToken: /home/shep/MCW/Hands-on lab/lab-files/ARM-template/post-provisioning.ps1:20
Line |
  20 |  … nerSASURI = New-AzStorageContainerSASToken -Context $destinationConte …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not get the storage context.  Please pass in a storage context or set the current storage context.

**Comment by timahenning** [comment] 2022-03-08 23:50
Hi @sqlshep,

I am struggling a little to find this exact code within MCW.  I just followed the instructions in this repo and successfully ran the script:

![image](https://user-images.githubusercontent.com/48766586/157345250-47be99b5-4ac8-4076-8593-f71fcbf290b8.png)

Did you try running BHOL in this repo?

Tim

**Comment by sqlshep** [comment] 2022-03-09 01:16
enough time has passed i pretty much forgot.  However, i was reviewing the arm template, and i think that you are selecting the container at location index [0] which was looking for a container with data in it, however there was a step where i had to open a cmd window in azure and i created the cmd storage in the same container, it happened to be at index [0], so whatever the arm template was looking for was not there. just guessing

**Comment by timahenning** [comment] 2022-03-09 14:38
Unfortunately, I cannot reproduce the issue and I am going to close this issue.  If you come across area of the lab this issue surfaces, we can reopen the issue.

**Closed by timahenning** 2022-03-09 14:38 UTC
